[project]
name = "query-agent"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "qingru97", email = "qingru97@gmail.com"},
]
dependencies = ["ollama>=0.4.7", "pytest>=8.3.5", "pydantic-settings>=2.8.1", "pydantic>=2.10.6", "huggingface-hub>=0.29.1", "numpy>=2.2.3", "asyncio>=3.4.3", "langchain>=0.3.20", "langchain-ollama>=0.2.3", "langgraph>=0.3.10", "grandalf>=0.8", "langgraph-cli[inmem]>=0.1.79", "fastapi>=0.115.12", "uvicorn>=0.34.0"]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false

[tool.pdm.scripts]
apiserver = "uvicorn apiserver:app --host 0.0.0.0 --port 8080 --workers 4"
start = "python graph.py"
# start = "python entry.py"
test = "pytest tests/"
working_dir = "."